import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-100 p-2">
        <p className="text-2x1 font-bold"> NextShop</p>
        <p> SeungHyun Hong </p>
      </div>
    </div>
  );
}
